name: On release

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

env:
  PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"
  
jobs:
  build_and_push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install shellcheck
        run: sudo apt-get install -y bash shellcheck
      - name: Analyse with shellcheck
        run: |
          shellcheck -V
          pushd ${GITHUB_WORKSPACE}/src
          shellcheck *
          popd
          pushd ${GITHUB_WORKSPACE}/tests
          shellcheck *
          popd
      - name: Install buildx
        uses: docker/setup-buildx-action@v2.7.0
      - name: Login to docker hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Run tests
        run: |
          echo "Start running tests"
          ${GITHUB_WORKSPACE}/tests/run_all_tests.sh ghcr.io/${{ github.repository }}
          echo "Done running tests"
      - name: Extract tag string
        id: git
        shell: bash
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          echo "image_tag=${RELEASE_VERSION}" >> ${GITHUB_OUTPUT}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Build and push ${{ github.repository }}:${{ steps.git.outputs.image_tag }}
        uses: docker/build-push-action@v4.1.1
        with:
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ github.repository }}:${{ steps.git.outputs.image_tag }}
            ${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.git.outputs.image_tag }}
            ghcr.io/${{ github.repository }}:latest
      - name: Update dockerhub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ github.repository }}
          short-description: ${{ github.event.repository.description }}
