name: shellcheck

on:
  push:
    paths:
      - 'src/*'
  pull_request:
    branches:
      - 'main'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install shellcheck
      run: sudo apt-get install -y bash shellcheck
    - name: Analyse with shellcheck
      run: |
        cd src
        shellcheck -V
        shellcheck *

